config/routes.rb
Rails.application.routes.draw do

  root :to => "articles#index"
  get 'articles/index'

  get 'articles/new'

  get 'articles/edit'
  resources :articles

  get "aktivasi" => "users#aktivasi", :as => "aktivasi"
  get 'users/index'

  get 'users/new'

  get 'users/edit'
  get "sign_up" => "users#new", :as => "sign_up"

  get 'comments/index'

  get 'comments/new'

  get 'comments/edit'
  
  resources :users
  resources :sessions
  resources :comments

  resources :articles do collection do
    post :import
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
	validates :title, presence: true,

                            length: { minimum: 5 }

    validates :content, presence: true,

                            length: { minimum: 10 }

    validates :status, presence: true

    scope :status_active, -> {where(status: 'active')}

    #name relation must plural
	has_many :comments
	has_many :user, through: :comments

	def self.import(file)
	  spreadsheet = Roo::Spreadsheet.open(file.path)
	  header = spreadsheet.row(1)
	  (2..spreadsheet.last_row).each do |i|
	  row = Hash[[header, spreadsheet.row(i)].transpose]
	  article = find_by(id: row["id"]) || new
	  article.attributes = row.to_hash
	  article.save!
  	  end
	end


	def self.open_spreadsheet(file)
	  case File.extname(file.original_filename)
	  when ".csv" then Roo::CSV.new(file.path, nil, :ignore)
	  when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
	  when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
	  else raise "Unknown file type: #{file.original_filename}"
	  end
	end




	def self.to_csv(options = {})
	  CSV.generate(options) do |csv|
	    csv << column_names
	    all.each do |article|
	      csv << article.attributes.values_at(*column_names)
	    end
	  end
	end

	def self.to_xls(options = {})
	  CSV.generate(options) do |xls|
	    xls << column_names
	    all.each do |article|
	      csv << article.attributes.values_at(*column_names)
	    end
	  end
	end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

belongs_to :article
belongs_to :user
 #has_many :families_homes
 #has_many :homes, through: :families_homes


        def default_status

            self.status = "active"

        end
end

app/models/resume.rb
class Resume < ActiveRecord::Base
	mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  	validates :name, presence: true # Make sure the owner's name is present.
end

app/models/user.rb
class User < ActiveRecord::Base
	 has_many :comments

    has_many :article, through: :comments

    attr_accessor :password
    before_save :add_salt_and_hash

    include Humanizer
    require_human_on :create

	validates :username, presence: true, uniqueness: true
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true, on: :create,
    length: { minimum: 5 },
    confirmation: true

    def add_salt_and_hash
        unless password.blank?
            self.password_salt = BCrypt::Engine.generate_salt
            self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
        end
    end

    before_create :add_activation_token
    def add_activation_token
        self.activation_token = SecureRandom.urlsafe_base64
        self.activation_status = "not activated"
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :check_current_user
        def current_user
            current_user ||= User.where("id = ? and activation_status = ?", session[:user], 'active').first
        end
        def check_current_user
            if current_user.blank?
                flash[:error] = "plase login first before run the action"
                redirect_to new_session_url
            else
                current_user
            end
        end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	
 before_action :check_current_user, only: [:index,:new, :create, :edit, :update, :destroy]
  
  def index
  	@articles = Article.page(params[:page]).per(5).order("id desc")
      respond_to do |format|
      format.html
      format.csv { send_data @articles.to_csv }
      format.xls { send_data @articles.to_csv(col_sep: "\t") }
    end
  end

  def new
  	@articles = Article.new
  end

  def create
    @articles = Article.new(params_articles)
    if @articles.save
        flash[:notice] = "Success Add Records"
        redirect_to action: 'index'
    else
        flash[:error] = "data not valid"
        render 'new'
    end
  end

  def edit
  	@article = Article.find_by_id(params[:id])
  end

  def update
 	   	@articles = Article.find_by_id(params[:id])
 	   	if @articles.update(params_articles)
    	flash[:notice] = "Success Update Records"
    	redirect_to action: 'index'
    	else
    	flash[:error] = "data not valid"
    	render 'edit'
    	end
   end

  def show
    @article = Article.find_by_id(params[:id])
    @comments = @article.comments.order("id desc")
    @comment = Comment.new
  end

  def destroy
	    @article = Article.find_by_id(params[:id])
	    if @article.destroy
	    flash[:notice] = "Success Delete a Records"
	    redirect_to action: 'index'
	    else
	    flash[:error] = "fails delete a records"
	    redirect_to action: 'index'
	    end

	end

  def import
    Article.import(params[:file])
    redirect_to root_url, notice: "Article imported."
  end


private
    def params_articles
        params.require(:article).permit(:title, :content, :status)
    end
        


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 


  before_action :check_current_user, only: [:new, :create, :edit, :update, :destroy]
  def index
  end



  def create
	@comment = Comment.new(params_comment)
    if @comment.save
        flash[:notice] = "Success Add Records"
        redirect_to action: 'index'
    else
        flash[:error] = "data not valid"
        render 'new'
    end
  end




  def edit
  end

  private
    def params_comment
		params.require(:comment).permit(:article_id, :user_id, :content, :status)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def edit
        user = User.find_by_activation_token(params[:id])
        if user.try(:update,{activation_token: "", activation_status: "active"})
            flash[:notice] = "Your account has active"
            redirect_to root_url
        else
            flash[:notice] = "Welcome to Rails 4"
            redirect_to root_url
        end
    end

    def create
        username = params[:username]
        password = params[:password]
        user = User.where("username =? and activation_status =?", username, "active").first
        user_password = BCrypt::Engine.hash_secret(password, user.password_salt) unless user.blank?
        if !user_password.blank? and user.password_hash.eql? user_password
            session[:user] = user.id
            flash[:notice] = "Welcome #{user.username}"
            redirect_to root_url
        else
            params[:username]
            flash[:error] = "Your data not valid"
            render "new"
        end
    end

    def destroy

        session[:user] = nil
        flash[:notice] = "logout session success"
        redirect_to root_url

    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  	@user = User.new
  end

  def create
        @user = User.new(params_user)
        if @user.save
            begin
                ConfirmationMailer.confirm_email("#{@user.email}", @user.activation_token).deliver
            rescue
                flash[:notice] = "activation instruction fails send to your email"
            end
            flash[:notice] = "activation instruction has send to #{@user.email}"
            redirect_to root_url
        else
            flash[:error] = "data not valid"
            render "new"
        end
  end

  def edit
  end

  def aktivasi
  	@user = User.all
  end

  private
    def params_user
        params.require(:user).permit(:username, :email, :password, 
        :password_confirmation, :humanizer_answer, :humanizer_question_id)

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/articles/_article.html.erb
<tr>

  <td><%= article.title.titleize %></td>

  <td><%= truncate(article.content, :length => 50, :separator => ' ') %></td>

</tr;

app/views/articles/_comments.html.erb
<% @comments.each do |comment| %>

        <p>

        <b><%= comment.user.try(:username) %></b>

        <br />

        <%= comment.content %>

        </p>

    <% end %>

app/views/articles/_form.html.erb
<div class="col-md-6">
	<%= form_for @comment, url: comments_path do |f| %>
	    <%= f.hidden_field :article_id, value: @article.id %>
	    <% if current_user %>
	            <%= f.hidden_field :user_id, value: current_user.id %>
	    <% end %>
	<div class="form-group">
	    <%= f.label :content %>
	    <%= f.text_area :content, :class => "form-control", rows: 10 %>
	</div>
	    <%= f.submit :submit %>
	<% end %>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= form_for @article do |f| %>
	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title, :class => "form-control"%>
	</div>

	<div class="form-group">
		<%= f.label :content %>
		<%= f.text_area :content, rows: 10, :class => "form-control"%>
	</div>
	<div class="form-group">
		<%= f.label :status %>
		<div class="checkbox">
			<label>
			<%= f.radio_button :status, "active" %>
			<%= label :article_status, 'active' %>
			</label>
		</div>
		<div class="checkbox">
			<label>
			<%= f.radio_button :status, "off" %>
			<%= label :article_status, 'off' %>
			</label>
		<div>
	</div>

	<%= f.submit :submit, :class => "btn btn-primary"%>
	<%= link_to "back to index", articles_path, :class => "btn btn-warning" %>
<% end %>
		

app/views/articles/index.html.erb
<div class="col-md-8">	
	<% @articles.each do |article| %>
	<h3 class="title"><%= article.title %></a></h3> 
	<p><%= article.content.truncate(50) %>  <%= link_to 'read more', article_path(article.id) %></p>
	<small>status : <i class="active"><%= article.status %></i></small> 
	</br>
	<div class="button-act">
	<ul>
		<li>
		<%= link_to "<button class='btn btn-success btn-xs'>Edit</button>".html_safe, edit_article_path(article.id) %>
		</li>
		<li>
		<%= button_to "delete", {:controller => :articles, :action => 'destroy', :id => article.id}, :method => :delete, :class =>'btn btn-danger btn-xs', data: {confirm: 'Are you sure that you wish to delete?'} %>
		</li>
	</ul>
	</div>
	<hr/>
	<% end %>

	<div class="paginate"><%= will_paginate @articles, renderer: BootstrapPagination::Rails %></div>
</div>

<div class="col-md-4">
	<h3>Import Article</h3>
	<div class="panel panel-default">
		<div class="panel-body">
			<%= form_tag import_articles_path, multipart: true do %>
			<div class="form-group">
			  <%= file_field_tag :file, :class => "form-control" %>
			</div>
			  <%= submit_tag "Import", :class =>'btn btn-success btn-xs' %>
			<% end %>
		</div>
	</div>

	<h3>Export Article</h3>
	<div class="panel panel-default">
		<div class="panel-body">
			Download:
  			<%= link_to "CSV", articles_path(format: "csv") %> |
  			<%= link_to "Excel", articles_path(format: "xls") %>
		</div>
	</div>
</div>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= form_for @articles do |f| %>

	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title, :class => "form-control"  %>
		<div class="alert-danger">
		<%= @articles.errors[:title].first unless @articles.errors[:title].blank? %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :content %>
		<%= f.text_area :content, rows: 10, :class => "form-control" %>
		<div class="alert-danger">
		<%= @articles.errors[:content].first unless @articles.errors[:content].blank? %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :status %>
		<div class="checkbox">
			<label>
			<%= f.radio_button :status, "active" %>
			<%= label :article_status, 'active' %>
			</label>
		</div>
		<div class="checkbox">
			<label>
			<%= f.radio_button :status, "off", :checked => true %>
			<%= label :article_status, 'off' %>
			</label>
		</div>
	</div>

	<%= f.submit :submit, :class => "btn btn-primary" %>

<% end %>

app/views/articles/show.html.erb
 <h3><%= @article.title %></h3>

<p><%= @article.content %></p>

<p><%= link_to 'back to index', articles_path %></p>

<div id="form-comment">

        <%= render 'form' %>

    </div>

 <div id="list-comments">

        <%= render 'comments' %>

    </div

app/views/comments/create.js.erb
<% if @comment.errors.present? %>

        $("#form-comment").html(" <%= j( render 'articles/form' ) %>");

    $($(".field_with_errors")[0]).append("<p class = 'message'> <%= escape_javascript( @comment.errors[:content].first ) %></p>");

        <% else %>

            $("#list-comments").html(" <%= j( render 'articles/comments' ) %>");

            $("#comment_content").val('');

            $("div.field_with_errors p.message").remove();

    <% end %>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Success</h1>
<p>Yours Comment has ben added</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coba Rails1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

</head>

<body>
<div id="custom-bootstrap-menu" class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header"><a class="navbar-brand" href="/">Rails-1</a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse navbar-menubuilder">
            <ul class="nav navbar-nav navbar-right">
                
                <% if !current_user %>
                <li><%= link_to 'Sign-Up', users_new_path %></li>
                <% else %>
                <li><a href="/">Home</a></li>
                <li><%= link_to "New Article", articles_new_path %></li>
                <li><a>Hello, <%= current_user.username %></a></li>
                <li><%= link_to 'Log-Out', session_path(current_user.id), method: "DELETE" %></li>
                <% end %>
            </ul>
        </div>
    </div>
</div>

<div class="konten">
	<div class="row">
		<div class="col-md-12">
		<%= yield %>
		</div>
	</div>
</div>


	

<script
              src="https://code.jquery.com/jquery-3.1.1.js"
              integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
              crossorigin="anonymous"></script>
</body>
</html>

app/views/users/aktivasi.html.erb
<% @user.each do |user| %>
<ul>
<li><%= link_to "Activate Your Account", "http://localhost:3000/sessions/#{@activation_token}/edit", method: 'GET' %> akun si <b><%= user.username %></b></li>
</ul>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>New User</h1>
<%= form_for @user do |f| %>

	<div class="form-group">
		<%= f.label :username %>
		<%= f.text_field :username, :class => "form-control" %>
		<div class="alert-danger">
		<%= @user.errors[:username].first unless @user.errors[:username].blank? %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :email %>
		<%= f.text_field :email, :class => "form-control" %>
		<div class="alert-danger">
		<%= @user.errors[:email].first unless @user.errors[:email].blank? %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :password %>
		<%= f.password_field :password, :class => "form-control" %>
		<div class="alert-danger">
		<%= @user.errors[:password].first unless @user.errors[:password].blank? %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation, :class => "form-control" %>
		<%= @user.errors[:password_confirmation].first unless @user.errors[:password_confirmation].blank? %>
	</div>
	<div class="form-group">
		<%= f.label :humanizer_answer, @user.humanizer_question %>
		<%= f.text_field :humanizer_answer, :class => "form-control" %>
		<%= f.hidden_field :humanizer_question_id %>
	</div>
<%= f.submit :submit, :class => "btn btn-primary" %>
<% end %>